version: "2"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_VERSION}
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
  es01:
    image: registry.gitlab.com/hedgehogai/full-lattice-search/full-lattice-search:${PLUGIN_VERSION}-${ES_VERSION}
    environment:
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms6144m -Xmx6144m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  esdata01:
    driver: local
